name: flavor_config
description: An easy to use package for creating flavors for any environment.

version: 2.0.1

homepage: https://github.com/zino-hofmann/flavor-config-flutter
repository: https://github.com/zino-hofmann/flavor-config-flutter
issue_tracker: https://github.com/zino-hofmann/flavor-config-flutter/issues

topics: [flutter, flavors, environment, config]

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  device_info_plus: ^12.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
